# Generated by Django 6.1.1 on 2026-09-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='casino/categories/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Game Category',
                'verbose_name_plural': 'Game Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='casino/providers/')),
                ('is_active', models.BooleanField(default=True)),
                ('integration_key', models.CharField(blank=True, help_text='Provider API identifier — keep private', max_length=200)),
            ],
            options={
                'verbose_name': 'Game Provider',
                'verbose_name_plural': 'Game Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CasinoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='casino/games/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='casino/games/thumbnails/')),
                ('rtp', models.DecimalField(blank=True, decimal_places=2, help_text='Return to player percentage (e.g. 96.50)', max_digits=5, null=True)),
                ('min_bet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_bet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('coming_soon', 'Coming Soon'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_new', models.BooleanField(db_index=True, default=False)),
                ('has_demo', models.BooleanField(default=False)),
                ('external_game_id', models.CharField(blank=True, db_index=True, help_text="Provider's game identifier for launch URLs", max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='casino.gamecategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='casino.gameprovider')),
            ],
            options={
                'verbose_name': 'Casino Game',
                'verbose_name_plural': 'Casino Games',
                'ordering': ['-is_featured', '-play_count', 'name'],
                'indexes': [models.Index(fields=['category', 'status'], name='casino_casi_categor_cd2b73_idx'), models.Index(fields=['provider', 'status'], name='casino_casi_provide_501e65_idx'), models.Index(fields=['is_featured', 'status'], name='casino_casi_is_feat_e79c40_idx')],
            },
        ),
    ]
