# Generated by Django 6.1.1 on 2026-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('announcement_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('promo', 'Promotion')], default='info', max_length=20)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optimized image for mobile viewports', null=True, upload_to='banners/mobile/')),
                ('target_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=50)),
                ('placement', models.CharField(choices=[('hero_carousel', 'Hero Carousel'), ('sidebar', 'Sidebar'), ('sportsbook_top', 'Sportsbook Top'), ('casino_top', 'Casino Top'), ('inline', 'Inline Content'), ('promotions_page', 'Promotions Page')], default='hero_carousel', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher = displayed first')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-priority', 'title'],
                'indexes': [models.Index(fields=['placement', 'is_active'], name='content_ban_placeme_3b873b_idx')],
            },
        ),
    ]
