# Generated by Django 6.1.1 on 2026-09-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportsbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Selection name, e.g. "Manchester United", "Over 2.5"', max_length=200)),
                ('decimal_odds', models.DecimalField(decimal_places=3, help_text='Decimal representation, e.g. 2.100', max_digits=10)),
                ('handicap', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('resulted', 'Resulted')], default='active', max_length=20)),
                ('result', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose'), ('void', 'Void'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='sportsbook.market')),
            ],
            options={
                'verbose_name': 'Odd',
                'verbose_name_plural': 'Odds',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OddsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='odds.odd')),
            ],
            options={
                'verbose_name': 'Odds History',
                'verbose_name_plural': 'Odds History',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='odd',
            index=models.Index(fields=['market', 'status'], name='odds_odd_market__0b6446_idx'),
        ),
        migrations.AddIndex(
            model_name='oddshistory',
            index=models.Index(fields=['odd', 'recorded_at'], name='odds_oddshi_odd_id_92d61c_idx'),
        ),
    ]
