# Generated by Django 6.1.1 on 2026-09-30 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('promotion_type', models.CharField(choices=[('welcome_bonus', 'Welcome Bonus'), ('free_bet', 'Free Bet'), ('deposit_match', 'Deposit Match'), ('cashback', 'Cashback'), ('enhanced_odds', 'Enhanced Odds'), ('casino_bonus', 'Casino Bonus'), ('loyalty', 'Loyalty Reward'), ('other', 'Other')], max_length=30)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('terms_and_conditions', models.TextField(help_text='Full T&Cs must be disclosed. Mandatory for legal compliance.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='promotions/thumbnails/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wagering_requirement', models.PositiveSmallIntegerField(blank=True, help_text='e.g. 30 means 30x rollover requirement', null=True)),
                ('max_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('forfeited', 'Forfeited')], default='pending', max_length=15)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_credited', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wagering_completed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Promotion',
                'verbose_name_plural': 'User Promotions',
                'unique_together': {('user', 'promotion')},
            },
        ),
    ]
