# Generated by Django 6.1.1 on 2026-09-30 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_code', models.CharField(help_text='Internal code used in code, e.g. stripe', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_deposits', models.BooleanField(default=True)),
                ('supports_withdrawals', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('max_deposit', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('max_withdrawal', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_providers/')),
            ],
            options={
                'verbose_name': 'Payment Provider Config',
                'verbose_name_plural': 'Payment Provider Configs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('e_wallet', 'E-Wallet'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('provider', models.CharField(help_text='e.g. stripe, paypal, skrill', max_length=100)),
                ('display_name', models.CharField(help_text='e.g. Visa **** 4242', max_length=100)),
                ('provider_token', models.CharField(blank=True, help_text='Provider-issued token, not raw card data', max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
