# Generated by Django 6.1.1 on 2026-09-30 21:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_type', models.CharField(choices=[('single', 'Single'), ('accumulator', 'Accumulator'), ('system', 'System')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void'), ('cashed_out', 'Cashed Out'), ('partially_cashed_out', 'Partially Cashed Out')], db_index=True, default='open', max_length=25)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('potential_return', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cash_out_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cashed_out_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bet',
                'verbose_name_plural': 'Bets',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_at_placement', models.DecimalField(decimal_places=3, max_digits=10)),
                ('selection_name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=300)),
                ('market_name', models.CharField(max_length=200)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void')], default='pending', max_length=10)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='bets.bet')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bet_selections', to='odds.odd')),
            ],
            options={
                'verbose_name': 'Bet Selection',
                'verbose_name_plural': 'Bet Selections',
            },
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status'], name='bets_bet_user_id_f8a082_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'placed_at'], name='bets_bet_user_id_e8ed50_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['status', 'placed_at'], name='bets_bet_status_c299f8_idx'),
        ),
    ]
