# Generated by Django 6.1.1 on 2026-09-30 21:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_stake', 'Bet Stake'), ('bet_win', 'Bet Win'), ('bet_refund', 'Bet Refund'), ('bonus_credit', 'Bonus Credit'), ('bonus_debit', 'Bonus Debit'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('payment_provider', models.CharField(blank=True, max_length=100)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'transaction_type'], name='wallet_tran_wallet__226144_idx'), models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__a053af_idx'), models.Index(fields=['status', 'created_at'], name='wallet_tran_status_58a2dc_idx')],
            },
        ),
    ]
